//------------------------------------------------------------------------------
// <auto-generated>
//     此代码已从模板生成。
//
//     手动更改此文件可能导致应用程序出现意外的行为。
//     如果重新生成代码，将覆盖对此文件的手动更改。
// </auto-generated>
//------------------------------------------------------------------------------

namespace BackstageWeb.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class db_Product
    {
        public int Id { get; set; }
        public string Name { get; set; }
        public string Introduce { get; set; }
        public string Image { get; set; }
        public Nullable<int> Count { get; set; }
        public string UnitPrice { get; set; }
        public Nullable<int> Type { get; set; }
        public Nullable<System.DateTime> CreateTime { get; set; }
        public Nullable<bool> IsNo { get; set; }
    }
}
