//------------------------------------------------------------------------------
// <auto-generated>
//     此代码已从模板生成。
//
//     手动更改此文件可能导致应用程序出现意外的行为。
//     如果重新生成代码，将覆盖对此文件的手动更改。
// </auto-generated>
//------------------------------------------------------------------------------

namespace BackstageWeb.Models
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class CompanyContext : DbContext
    {
        public CompanyContext()
            : base("name=CompanyContext")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<db_Case> db_Case { get; set; }
        public virtual DbSet<db_Menu> db_Menu { get; set; }
        public virtual DbSet<db_News> db_News { get; set; }
        public virtual DbSet<db_Product> db_Product { get; set; }
        public virtual DbSet<db_ProductType> db_ProductType { get; set; }
        public virtual DbSet<db_Users> db_Users { get; set; }
        public virtual DbSet<db_Company> db_Company { get; set; }
    }
}
